on:
  release:
      types: [published]
  
env:
    CDN_TOKEN: ${{secrets.CDN_TOKEN}}

jobs:
    trigger-cdn-update:
        runs-on: ubuntu-latest

        steps:
        - name: Make CDN Update Request
          run: |
            curl "https://cdn.unyt.org/update/$GITHUB_REPOSITORY?token=$CDN_TOKEN"
    