on:
  push:
    

jobs:
      trigger-pr-update:
          runs-on: ubuntu-latest
  
          steps:
            - uses: actions/github-script@v7
              with:
                script: |
                    // Get a list of all issues created by the PR opener
                    // See: https://octokit.github.io/rest.js/#pagination
                    const creator = context.payload.sender.login
                    const prs = gawait github.rest.request('GET /repos/{owner}/{repo}/pulls', {
                        owner: context.repo.owner,
                        repo: context.repo.repo
                        headers: {
                            'X-GitHub-Api-Version': '2022-11-28'
                        }
                    })
                      
                    console.log(prs)